# Image dimensions
dimensions:
  portrait_size: [1080, 1920]  # width x height
  landscape_size: [1920, 1080]  # width x height

# Immich configuration
immich:
  url: "http://{IMMICH_URL_HERE}:2283"
  api_key: "TKpvjF35ioeaC5eIsnFTHNkFmG7nC8fYjxxu0h1RCYE"
  input_album_id: "789e4fbf-14ca-42bb-ad4e-0d8a27814fb9"
  output_album_id: "66e9d580-e362-4d69-8eb3-d8fb3925de4c"

# Meural Canvas configuration
meural:
  username: "your_meural_username"
  password: "your_meural_password"
  playlist_id: "123456"
  devices:
    - name: "Living Room"
      ip: "192.168.1.136"
      preview_duration: 10  # seconds
    - name: "Sitting Room"
      ip: "192.168.1.135"
      preview_duration: 10  # seconds
